"""
Stage 1 — Skeleton-Targeted Retrieval (70% Structured + 30% Exploratory)

For each QuestionSkeleton:
  - Build structured queries: one per unique source_concept in sub_concepts
  - Generate exploratory queries: LLM creates novel query angles
  - Pinecone retrieval: 20 fetched → cross-encode → MMR select 5 per query
  - Google Search: CA context if ca_flag=True
  - Tier 3 (web_only): skip Pinecone entirely

Returns a RetrievalResult per skeleton — with variable chunk count:
  - Each query: 5 chunks (20 fetched → cross-encode → MMR select 5)
  - Per skeleton: (number_of_queries) × 5 chunks
  - Example: 2 queries = 10 chunks, 3 queries = 15 chunks, 1 query = 5 chunks

Retrieval pipeline per query (v2 enhanced):
  1. Over-fetch: 20 candidates from Pinecone
  2. Cross-encoder re-rank: score all 20 by relevance to query
  3. Client-side MMR: mmr_select_from_chunks() picks 5 diverse final chunks (lambda randomized: 30%/0.7, 40%/0.5, 30%/0.3)
"""
from __future__ import annotations

import asyncio
import json
import logging
import random
from collections import defaultdict
from dataclasses import dataclass, field
from typing import List, Optional, Dict

from pydantic import BaseModel

logger = logging.getLogger(__name__)


# ── LLM Response Models ───────────────────────────────────────────────────────

class ExploratoryQueriesResponse(BaseModel):
    """LLM-generated exploratory queries for corpus discovery."""
    queries: List[str] = []  # List of 3 novel query strings

# Chunk budget constants (default)
_OWN_CONCEPT_K      = 5
_BORROWED_CONCEPT_K = 3
_MAX_CHUNKS_TOTAL   = 10

# Retrieval quality constants
_OVERFETCH_MULTIPLIER = 3    # fetch this many × k candidates before re-rank + MMR
_MMR_LAMBDA           = 0.6  # relevance weight (0=max diversity, 1=max relevance)

# Difficulty-type-aware MMR lambda values
# Easy = high relevance (tight precision), Hard = lower relevance (more diversity)
_DIFFICULTY_LAMBDA = {
    "easy_recall_static": 0.8,
    "easy_ca_trigger": 0.8,
    "easy_reverse_mild": 0.7,
    "medium_concept_linking_same_domain": 0.6,
    "medium_adjacent_fact": 0.6,
    "medium_statistical_reversal": 0.6,
    "medium_precision_location": 0.6,
    "medium_ca_integration": 0.5,
    "hard_counterintuitive_single_concept": 0.5,
    "hard_cross_domain_linking": 0.4,
    "hard_all_of_above_precision": 0.5,
    "hard_strong_concept_depth": 0.5,
    "hard_spatial_sequence": 0.5,
    "hard_reverse_extreme": 0.4,
    "pure_ca_news_tracking": 0.7,
    "pure_ca_recent_event": 0.7,
}

# ── Exploratory Query Dimensions (UPSC-relevant angles) ──────────────────────
# These are intelligently allocated based on difficulty, not randomly generated by LLM
_EXPLORATORY_DIMENSIONS = [
    "cross_domain",        # How concept relates to other domains/subjects
    "temporal",            # Historical evolution or recent developments
    "anomaly",             # Edge cases, exceptions, unusual scenarios
    "extreme",             # Extreme conditions or magnitudes
    "linked_concept",      # Deep linking to another major concept
    "application",         # Practical application or real-world impact
    "comparison",          # Comparison with similar concept
    "policy",              # Policy implications or government response
]

# Difficulty-based query count & exploratory allocation
# Format: [min, max] for both structured and exploratory bounds
_QUERY_ALLOCATION = {
    "easy": {
        "structured": [1, 2],  # 1-2 structured queries
        "exploratory": [0, 0], # 0 exploratory (no exploration for easy)
    },
    "medium": {
        "structured": [1, 2],  # 1-2 structured queries
        "exploratory": [0, 1], # 0-1 exploratory (optional)
    },
    "hard": {
        "structured": [2, 3],  # 2-3 structured queries (deep linkages)
        "exploratory": [1, 2], # 1-2 exploratory (always included)
    },
}

# Query bounds by difficulty
def _get_query_bounds(skeleton) -> tuple[int, tuple[int, int]]:
    """
    Determine structured query count and exploratory query bounds based on difficulty.

    Returns: (structured_count, (expl_min, expl_max))

    Easy: 1-2 structured, 0 exploratory
    Medium: 1-2 structured, 0-1 exploratory
    Hard: 2-3 structured, 1-2 exploratory

    Decision logic:
    - Structured: Use max if sub_concepts >= 2 OR has linked_concept, else min
    - Exploratory bounds: Return min/max from allocation; LLM decides within bounds
    """
    difficulty = skeleton.difficulty
    allocation = _QUERY_ALLOCATION.get(difficulty, _QUERY_ALLOCATION["medium"])

    # Analyze skeleton structure
    sub_concept_count = len(skeleton.sub_concepts)
    has_linked_concept = any(sc.source_concept for sc in skeleton.sub_concepts)

    # Decide structured count: use max if complex, else min
    struct_min, struct_max = allocation["structured"]
    if sub_concept_count >= 2 or has_linked_concept:
        struct_count = struct_max
    else:
        struct_count = struct_min

    # Return exploratory bounds (LLM will decide within these)
    expl_min, expl_max = allocation["exploratory"]
    expl_bounds = (expl_min, expl_max)

    return struct_count, expl_bounds

# Randomized MMR lambda for exploratory diversity
def _pick_random_mmr_lambda() -> float:
    """Randomize MMR lambda: 30% high relevance, 40% balanced, 30% high diversity."""
    r = random.random()
    if r < 0.30:
        return 0.7  # High relevance (tight)
    elif r < 0.70:
        return 0.5  # Balanced
    else:
        return 0.3  # High diversity (exploratory)

# Difficulty-type-aware budget adjustments
# Easy = tight retrieval (precision), Hard = exploratory retrieval (recall)
_DIFFICULTY_BUDGET = {
    "easy_recall_static": {"own": 3, "borrowed": 2, "total": 7},
    "easy_ca_trigger": {"own": 3, "borrowed": 1, "total": 6},
    "easy_reverse_mild": {"own": 4, "borrowed": 2, "total": 8},
    "medium_concept_linking_same_domain": {"own": 5, "borrowed": 3, "total": 10},
    "medium_adjacent_fact": {"own": 5, "borrowed": 3, "total": 10},
    "medium_statistical_reversal": {"own": 5, "borrowed": 2, "total": 10},
    "medium_precision_location": {"own": 5, "borrowed": 2, "total": 10},
    "medium_ca_integration": {"own": 4, "borrowed": 3, "total": 10},
    "hard_counterintuitive_single_concept": {"own": 6, "borrowed": 4, "total": 12},
    "hard_cross_domain_linking": {"own": 5, "borrowed": 5, "total": 12},
    "hard_all_of_above_precision": {"own": 7, "borrowed": 5, "total": 14},
    "hard_strong_concept_depth": {"own": 6, "borrowed": 3, "total": 12},
    "hard_spatial_sequence": {"own": 6, "borrowed": 4, "total": 12},
    "hard_reverse_extreme": {"own": 6, "borrowed": 4, "total": 12},
    "pure_ca_news_tracking": {"own": 3, "borrowed": 1, "total": 6},
    "pure_ca_recent_event": {"own": 3, "borrowed": 1, "total": 6},
}


# ── LLM Query Generator ───────────────────────────────────────────────────────

async def _generate_exploratory_queries(
    skeleton,
    gemini_client,
    min_queries: int = 0,
    max_queries: int = 2,
) -> List[str]:
    """
    LLM generates exploratory queries to explore angles NOT covered by skeleton.

    Difficulty-based bounds:
      - Easy: 0 exploratory (min=0, max=0)
      - Medium: 0-1 exploratory (min=0, max=1)
      - Hard: 1-2 exploratory (min=1, max=2)

    Input to LLM:
      - concept
      - sub_concepts tested
      - aspects covered
      - difficulty_type
      - min/max query bounds

    Output: Variable number of queries (between min and max) exploring:
      - Different aspects (economic, historical, climate, policy)
      - Inter-domain connections (Monsoon + Agriculture, Monsoon + Migration)
      - Novel angles (extreme events, case studies, recent trends, linkages)

    The LLM decides the count within bounds based on skeleton complexity.
    """
    if not gemini_client:
        logger.warning("[Stage1] No Gemini client — skipping exploratory query generation")
        return []

    if max_queries == 0:
        logger.info(
            f"[Stage1] {skeleton.skeleton_id} | Exploratory queries disabled "
            f"(difficulty='{skeleton.difficulty}', bounds=[{min_queries}, {max_queries}])"
        )
        return []

    concept = skeleton.concept
    sub_concept_topics = [sc.topic for sc in skeleton.sub_concepts]
    aspects_covered = list(set(sc.aspect for sc in skeleton.sub_concepts))
    difficulty = skeleton.difficulty

    system_prompt = """You are an expert UPSC curriculum researcher.
Given a question skeleton and query bounds, generate exploratory Pinecone search queries
to explore DIFFERENT angles and connections NOT covered by the skeleton.

Think about:
- Different aspects (economic, historical, climate, policy, social, environmental)
- Inter-domain links (concept + agriculture, concept + migration, concept + policy)
- New dimensions (extreme cases, recent events, case studies, linkages to other concepts)
- Avoid repeating the sub_concepts already tested

Generate SHORT, specific queries (5-10 words each) that a corpus would have.
Respect the min/max bounds based on skeleton complexity."""

    query_count_instruction = (
        f"Generate between {min_queries} and {max_queries} exploratory queries. "
        f"If the skeleton is simple, use fewer; if complex with many inter-domain links, use more."
    )

    user_prompt = f"""
QUESTION SKELETON:
  Concept: {concept}
  Sub-concepts tested: {sub_concept_topics}
  Aspects covered: {aspects_covered}
  Difficulty: {difficulty}

QUERY COUNT GUIDANCE:
  {query_count_instruction}

Return ONLY a JSON object with a "queries" array of strings (0-{max_queries} items).
"""

    try:
        response = await gemini_client.generate_response(
            user_prompt=user_prompt,
            system_prompt=system_prompt,
            response_schema=ExploratoryQueriesResponse,
            temperature=0.7,  # Some creativity for novel angles
        )

        if isinstance(response, str):
            parsed = json.loads(response)
            queries = parsed.get("queries", [])
        else:
            queries = response.queries if hasattr(response, "queries") else []

        # Clamp to bounds
        if len(queries) > max_queries:
            queries = queries[:max_queries]
        if len(queries) < min_queries:
            queries = queries + [""] * (min_queries - len(queries))
            queries = [q for q in queries if q]  # Remove empties

        logger.info(
            f"[Stage1] {skeleton.skeleton_id} | Exploratory queries: "
            f"difficulty='{difficulty}', bounds=[{min_queries}, {max_queries}], "
            f"LLM generated={len(queries)}, "
            f"queries={queries}"
        )
        return queries
    except Exception as e:
        logger.warning(
            f"[Stage1] {skeleton.skeleton_id} | Exploratory query generation failed "
            f"(difficulty='{difficulty}', bounds=[{min_queries}, {max_queries}]): {e}"
        )
        return []


# ── Data classes ──────────────────────────────────────────────────────────────

@dataclass
class RetrievalResult:
    skeleton_id:    str
    static_chunks:  List[Dict]          # from Pinecone
    ca_context:     str                 # from Google Search (raw text)
    ca_queries:     List[str]           # the queries that were run
    retrieval_mode: str                 # pinecone | pinecone_fuzzy | web_only
    query_metadata: List[Dict] = field(default_factory=list)  # {query_text, is_exploratory, mmr_lambda, chunk_count}


# ── Pinecone query builder ────────────────────────────────────────────────────

def _build_structured_queries(skeleton) -> List[Dict]:
    """
    Build 70% STRUCTURED queries from skeleton.sub_concepts.

    One query per unique source_concept in skeleton.sub_concepts.
    Marked as is_exploratory=False for tracking.

    Returns list of:
      {"query_text": str, "concept_filter": str, "k": int, "is_exploratory": bool}

    source_concept="" means sub_concept belongs to skeleton's own concept.
    """
    # Group sub_concepts by source_concept
    groups: Dict[str, List[str]] = defaultdict(list)
    for sc in skeleton.sub_concepts:
        src = sc.source_concept if sc.source_concept else skeleton.concept
        groups[src].append(sc.topic)

    queries = []
    own_concept = skeleton.concept

    for source, topics in groups.items():
        # Build query text: concept name + sub_concept topics joined
        query_text = f"{source} {' '.join(t[:60] for t in topics)}"

        queries.append({
            "query_text":      query_text,
            "concept_filter":  source,
            "k":               5,  # Will be allocated per-query in retrieval
            "is_exploratory":  False,
        })

    # Log what we're about to fire
    for q in queries:
        label = "own" if q["concept_filter"] == own_concept else "borrowed"
        logger.info(
            f"[Stage1][StructuredQuery] [{label}] concept='{q['concept_filter']}' "
            f"→ '{q['query_text'][:80]}'"
        )
    return queries


# ── Google Search query builder ───────────────────────────────────────────────

def _build_ca_search_queries(skeleton) -> List[str]:
    """
    Build Google Search queries for a CA-flagged skeleton (70% structured + 30% exploratory).

    70% Structured:
      1. skeleton.ca_event (most targeted, if present)
      2. Static concept + topic search (from sub_concepts)

    30% Exploratory:
      3. "{concept} latest developments" (recent news angle)
      4. "{concept} policy impact current" (policy + impact angle)

    Returns list of query strings for Gemini Google Search tool.
    """
    queries = []

    # 70% STRUCTURED
    # Query 1: ca_event from blueprint (most targeted)
    if skeleton.ca_event:
        queries.append(
            f"{skeleton.ca_event} {skeleton.concept} India 2024 2025 official"
        )
    else:
        # Fallback: concept + first topic
        first_topic = skeleton.sub_concepts[0].topic[:50] if skeleton.sub_concepts else ""
        queries.append(
            f"{skeleton.concept} {first_topic} UPSC Prelims 2024 2025 India"
        )

    # Query 2: Government source anchor (static content)
    first_topic = skeleton.sub_concepts[0].topic[:50] if skeleton.sub_concepts else ""
    queries.append(
        f"site:pib.gov.in OR site:indiabudget.gov.in OR site:moes.gov.in "
        f"{skeleton.concept} {first_topic}"
    )

    # 30% EXPLORATORY
    # Query 3: Recent developments / latest news
    queries.append(
        f"{skeleton.concept} latest developments 2024 2025 news India"
    )

    # Query 4: Policy impact / implications
    queries.append(
        f"{skeleton.concept} policy impact implementation India current"
    )

    logger.info(
        f"[Stage1][CAQuery] {skeleton.skeleton_id} | {len(queries)} CA search queries "
        f"(2 structured, 2 exploratory):"
    )
    for i, q in enumerate(queries, 1):
        query_type = "structured" if i <= 2 else "exploratory"
        logger.info(f"  [{i}] [{query_type}] {q[:90]}")
    return queries



async def _retrieve_from_pinecone(
    queries:         List[Dict],
    pinecone_handler,
    subject:         str,
    retrieval_mode:  str,
    difficulty_type: str = "",
) -> tuple[List[Dict], List[Dict]]:
    """
    70% STRUCTURED + 30% EXPLORATORY Pinecone retrieval.

    Per query:
      1. Fetch k=20 (over-fetch for recall)
      2. Cross-encoder re-rank all candidates
      3. MMR select k=5 with RANDOMIZED lambda:
         - 30%: lambda=0.7 (high relevance, tight)
         - 40%: lambda=0.5 (balanced)
         - 30%: lambda=0.3 (high diversity, exploratory)

    Total output: ~65 chunks (13 queries × 5 chunks) + metadata

    Enriches with SQLite full text.

    Returns:
      (all_chunks, query_metadata) where query_metadata tracks source query info
    """
    if not queries:
        return [], []

    all_chunks    = []
    seen_ids      = set()
    query_metadata = []
    content_store = getattr(pinecone_handler, "content_store", None)
    embedder      = getattr(pinecone_handler, "langchain_embeddings", None)

    # ── Batch embed all query texts in ONE API call ───────────────────────────
    vectors: List[Optional[List[float]]] = [None] * len(queries)
    if embedder:
        try:
            texts  = [q["query_text"] for q in queries]
            batch  = embedder.embed_documents(texts)   # one call for all N queries
            vectors = batch
            logger.info(f"[Stage1] Batch-embedded {len(texts)} queries in 1 API call")
        except Exception as e:
            logger.warning(f"[Stage1] Batch embedding failed, falling back to per-query: {e}")

    # ── Per-query Pinecone call (over-fetch 20 → cross-encoder → MMR select 5) ─────────
    for i, q in enumerate(queries):
        filter_meta = {"source_type": {"$ne": "pyq"}}
        if retrieval_mode == "pinecone":
            filter_meta["major_domain"] = {"$in": [q["concept_filter"], subject]}

        query_vec  = vectors[i] if vectors[i] is not None else None
        target_k   = 5  # Final MMR selection: 5 chunks per query
        overfetch_k = 20  # Over-fetch: start with 20 candidates

        is_exploratory = q.get("is_exploratory", False)
        query_type_label = "exploratory" if is_exploratory else "structured"

        # Pick randomized MMR lambda for diversity
        mmr_lambda = _pick_random_mmr_lambda()

        try:
            # Fetch 20 candidates, enrich ALL from SQL, cross-encoder re-ranks all, then MMR picks 5
            chunks = pinecone_handler.query_documents(
                query_text        = q["query_text"],
                k                 = target_k,
                fetch_k           = overfetch_k,
                re_rank           = True,
                filter_metadata   = filter_meta,
                use_content_store = True,  # Enrich ALL 20 from SQL BEFORE cross-encoding
                query_vector      = query_vec,
            )
        except Exception as e:
            logger.warning(f"[Stage1] Pinecone query failed for '{q['concept_filter']}': {e}")
            chunks = []

        # Fuzzy fallback if sparse (< half requested)
        if len(chunks) < max(1, target_k // 2):
            try:
                chunks = pinecone_handler.query_documents(
                    query_text        = q["query_text"],
                    k                 = target_k,
                    fetch_k           = overfetch_k,
                    re_rank           = True,
                    filter_metadata   = {"source_type": {"$ne": "pyq"}},
                    use_content_store = True,  # Enrich ALL from SQL BEFORE cross-encoding
                    query_vector      = query_vec,
                )
                logger.debug(f"[Stage1] Fuzzy fallback: '{q['concept_filter']}' → {len(chunks)} chunks")
            except Exception as e:
                logger.warning(f"[Stage1] Fuzzy fallback failed: {e}")

        # ── Chunk deduplication & validation (NO SECOND ENRICHMENT) ────────────
        # query_documents() already enriched ALL 20 chunks from SQL.
        # Cross-encoder selected top 5. Just validate they have content.
        enriched_count = 0
        for chunk in chunks:
            chunk_id = chunk.get("id") or chunk.get("chunk_id") or id(chunk)
            if chunk_id in seen_ids:
                continue
            seen_ids.add(chunk_id)

            # Chunks should already be enriched by query_documents().
            # Only fallback to metadata if somehow content is missing.
            if not chunk.get("content"):
                chunk["content"] = chunk.get("metadata", {}).get("content_preview", "")
            else:
                enriched_count += 1

            all_chunks.append(chunk)

        logger.info(
            f"[Stage1] [{query_type_label}] concept='{q['concept_filter'][:30]}' | "
            f"query='{q['query_text'][:60]}' → {len(chunks)} chunks "
            f"(lambda={mmr_lambda:.1f}, enriched={enriched_count})"
        )

        # Track metadata for this query
        query_metadata.append({
            "query_text": q["query_text"],
            "is_exploratory": is_exploratory,
            "mmr_lambda": mmr_lambda,
            "chunk_count": len(chunks),
            "enriched_count": enriched_count,
        })

    # ── NO FINAL DEDUP — Keep all chunks for rich context ────────────────────
    # With 70% structured + 30% exploratory, having 65 chunks gives Stage 3 LLM
    # massive exploration room. Semantic dedup already happened per-query via MMR.
    logger.info(
        f"[Stage1] Collected {len(all_chunks)} total chunks "
        f"({len([m for m in query_metadata if not m['is_exploratory']])} structured, "
        f"{len([m for m in query_metadata if m['is_exploratory']])} exploratory)"
    )

    return all_chunks, query_metadata


# ── Main retrieval function ───────────────────────────────────────────────────

async def retrieve_for_skeleton(
    skeleton,
    pinecone_handler,
    gemini_client,
    subject: str,
) -> RetrievalResult:
    """
    Full retrieval for one skeleton: 70% structured + 30% exploratory (except pure CA).

    TWO TYPES OF RETRIEVAL:

    1. PURE CA QUESTIONS (pure_ca=True):
       - Skip Pinecone retrieval entirely
       - Google Search ONLY (mandatory)
       - Result: ca_context (bullet points from event searches)

    2. CA-LINKED / REGULAR QUESTIONS (pure_ca=False):
       - Build structured queries from skeleton.sub_concepts (variable count)
       - LLM generates exploratory queries (variable count)
       - Pinecone retrieval: fetch 20 per query, MMR select 5 (randomized lambda)
       - Result: (query_count × 5) chunks for that skeleton
         Example: 2 queries → 10 chunks, 3 queries → 15 chunks, 1 query → 5 chunks
       - Google Search for CA (if ca_flag=True, optional for CA-linking)
    """
    retrieval_mode = getattr(skeleton, "retrieval_mode", "pinecone")

    static_chunks = []
    ca_context    = ""
    ca_queries    = []
    query_metadata = []

    # ── Pinecone retrieval: 70% structured + 30% exploratory ────────────────────
    # SKIP for pure CA questions (no concept retrieval needed, only CA search)
    is_pure_ca = getattr(skeleton, "pure_ca", False)

    if is_pure_ca:
        logger.info(
            f"[Stage1] {skeleton.skeleton_id} | Pure CA question — skipping Pinecone retrieval, CA search only"
        )
    elif retrieval_mode != "web_only":
        # Determine query count bounds based on difficulty
        difficulty = skeleton.difficulty
        struct_count, (expl_min, expl_max) = _get_query_bounds(skeleton)

        logger.info(
            f"[Stage1] {skeleton.skeleton_id} | Query bounds for difficulty='{difficulty}': "
            f"structured={struct_count}, exploratory=[{expl_min}, {expl_max}]"
        )

        # Build structured queries from skeleton.sub_concepts
        all_structured = _build_structured_queries(skeleton)
        structured_queries = all_structured[:struct_count]

        # Generate exploratory queries from LLM (within bounds)
        exploratory_query_texts = await _generate_exploratory_queries(
            skeleton,
            gemini_client,
            min_queries=expl_min,
            max_queries=expl_max
        )
        exploratory_queries = [
            {
                "query_text": qt,
                "concept_filter": skeleton.concept,
                "k": 5,
                "is_exploratory": True,
            }
            for qt in exploratory_query_texts
        ]

        # Combine all queries
        all_queries = structured_queries + exploratory_queries

        # Retrieve from Pinecone
        static_chunks, query_metadata = await _retrieve_from_pinecone(
            queries=all_queries,
            pinecone_handler=pinecone_handler,
            subject=subject,
            retrieval_mode=retrieval_mode,
            difficulty_type=difficulty,
        )

        logger.info(
            f"[Stage1] {skeleton.skeleton_id} | Pinecone retrieval complete: "
            f"{len(static_chunks)} chunks from {len(all_queries)} queries "
            f"(difficulty='{difficulty}', {len(structured_queries)} structured, "
            f"{len(exploratory_queries)} exploratory [bounds={expl_min}-{expl_max}])"
        )

    # ── Google Search retrieval ───────────────────────────────────────────────
    # MANDATORY for pure CA questions, OPTIONAL for CA-linked questions
    if skeleton.ca_flag:
        ca_queries = _build_ca_search_queries(skeleton)
        try:
            # Pass queries to Gemini client that has Google Search tool enabled
            search_result = await gemini_client.search_and_summarise(
                queries=ca_queries,
                context_hint=f"UPSC Prelims {subject} — {skeleton.concept}",
            )
            ca_context = search_result or ""

            if is_pure_ca:
                logger.info(
                    f"[Stage1] {skeleton.skeleton_id} | Pure CA question — CA search result: "
                    f"{len(ca_context)} chars (ONLY source)"
                )
            else:
                logger.info(
                    f"[Stage1] {skeleton.skeleton_id} | CA-linked question — CA search: "
                    f"{len(ca_context)} chars (linked to concept retrieval)"
                )
        except Exception as e:
            logger.warning(f"[Stage1] {skeleton.skeleton_id} | CA search failed: {e}")
            if is_pure_ca:
                logger.error(f"[Stage1] {skeleton.skeleton_id} | ❌ CRITICAL: Pure CA question has no CA context!")

    return RetrievalResult(
        skeleton_id   = skeleton.skeleton_id,
        static_chunks = static_chunks,
        ca_context    = ca_context,
        ca_queries    = ca_queries,
        retrieval_mode= retrieval_mode,
        query_metadata= query_metadata,
    )


# ── Batch retrieval (all skeletons in parallel, semaphore-limited) ────────────

async def retrieve_for_all_skeletons(
    skeletons,
    pinecone_handler,
    gemini_client,
    subject:     str,
    concurrency: int = 10,
) -> List[RetrievalResult]:
    """
    Run retrieval for all skeletons concurrently.
    Google Search calls are rate-limited by semaphore.
    Pinecone calls are fast enough to run fully parallel.
    """
    semaphore = asyncio.Semaphore(concurrency)

    async def bounded(skeleton):
        async with semaphore:
            return await retrieve_for_skeleton(
                skeleton, pinecone_handler, gemini_client, subject
            )

    results = await asyncio.gather(*[bounded(s) for s in skeletons])
    logger.info(f"[Stage1] Retrieval complete: {len(results)} skeletons")
    return results
