import asyncio
import sys
import logging
from pathlib import Path
import json

# Configure logging to be clean but informative
logging.basicConfig(
    level=logging.INFO,
    format='%(message)s'
)
logger = logging.getLogger(__name__)

# Add backend to sys.path
backend_dir = Path(__file__).resolve().parent.parent.parent.parent
sys.path.append(str(backend_dir))

from app.utils.dimension_current_affairs.pipeline import run_dimension_pipeline, generate_dimension_plan
from app.utils.dimension_current_affairs.gemini_search_pipeline import run_gemini_search_dimension_pipeline

async def compare_pipelines(topic: str):
    print("\n" + "="*80)
    print(f"PIPELINE COMPARISON FOR TOPIC: {topic}")
    print("="*80 + "\n")

    # 1. RUN MAP/NEWSAPI PIPELINE (Original)
    print("🚀 [PIPELINE A] Map/NewsAPI Current Affairs Pipeline")
    print("-" * 50)
    try:
        # We also want to log the dimension queries for this one
        plan = await generate_dimension_plan(topic)
        print(f"🔍 [A] Planning Stage Dimensions & Queries:")
        for dim in plan.dimensions:
            print(f"   • {dim.dimension}: {', '.join(dim.search_queries)}")
        
        print(f"\n✨ [A] Running full pipeline...")
        a_bullets = await run_dimension_pipeline(topic)
        
        print(f"\n✅ [A] Results ({len(a_bullets)} bullets):")
        for i, b in enumerate(a_bullets, 1):
            print(f"   {i}. {b}")
    except Exception as e:
        print(f"❌ [A] Failed: {e}")

    print("\n" + "="*50 + "\n")

    # 2. RUN GEMINI SEARCH PIPELINE (New)
    print("🚀 [PIPELINE B] Gemini Google Search Tool Pipeline")
    print("-" * 50)
    try:
        # This pipeline does planning internally
        print(f"✨ [B] Running full pipeline...")
        b_result = await run_gemini_search_dimension_pipeline(topic)
        
        print(f"\n🔍 [B] Planning Stage Dimensions (as generated by Gemini):")
        for dim in b_result.dimensions:
            print(f"   • {dim.dimension}")
            
        print(f"\n✅ [B] Results ({sum(len(d.bullets) for d in b_result.dimensions)} bullets):")
        for dim in b_result.dimensions:
            print(f"\n   🔹 {dim.dimension}:")
            for i, bullet in enumerate(dim.bullets, 1):
                print(f"     {i}. {bullet}")
    except Exception as e:
        print(f"❌ [B] Failed: {e}")

    print("\n" + "="*80)
    print("COMPARISON COMPLETE")
    print("="*80 + "\n")

if __name__ == "__main__":
    # Test topic - user can override via command line
    test_topic = sys.argv[1] if len(sys.argv) > 1 else "Examine the role of Agnipath Scheme in moderning India's defense forces."
    
    asyncio.run(compare_pipelines(test_topic))
